name: 🛰 Discord Notifications

# Триггеры
on:
  push:
    branches:
      - '**'  # ловим все ветки
  pull_request:
    types: [opened, closed, merged]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # Получаем код (нужно для github.event.head_commit)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Push уведомление
      - name: 📨 Discord Push Notification
        if: github.event_name == 'push'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: OSS 117
          DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
        with:
          args: |
            📢 **Push в репозиторий** `${{ github.repository }}`
            🧑 Автор: `${{ github.actor }}`
            🌿 Ветка: `${{ github.ref_name }}`
            📝 Сообщение коммита: `${{ github.event.head_commit.message }}`
            🔗 [Смотреть коммит](${{ github.event.head_commit.url }})

      # Pull Request уведомление
      - name: 💬 Discord PR Notification
        if: github.event_name == 'pull_request'
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DISCORD_USERNAME: OSS 117
          DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
        with:
          args: |
            🎯 **Pull Request ${{ github.event.action }}**
            📦 [#${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }})
            🧑 Автор: `${{ github.actor }}`
            📝 Название PR: `${{ github.event.pull_request.title }}`
